:start:
BOOK IV

The Spartan king Menelaus and his bride Helen interrupted their double wedding feast of the (separate) marriages of their son and daughter to host Telemachus.  Menelaus and Helen share stories with Telemachus, among them Odysseus's wooden horse and Menelaus' necessary capture of the god Proteus, the Old Man of the Sea, in Egypt, from whom he learned, among other things, that Odysseus was trapped on an Calypso's island, but alive.

Back at Odysseus's house, the suitors planned to kill Telemachus.


